modLoader="javafml"
loaderVersion="[38,)"
license="GPLv3"
issueTrackerURL="https://github.com/MrCrayfish/GlassCutter/issues"

[[mods]]
modId="glasscutter"
version="1.1.1"
displayName="Glasscutter"
updateJSONURL="https://mrcrayfish.com/modupdatejson?id=glasscutter"
displayURL="https://mrcrayfish.com/mods?id=glasscutter"
logoFile="glasscutter.png"
credits="@DarkestArgentum on Twitter for ideas"
authors="MrCrayfish"
description='This is a simple mod that adds a glass cutter into the game. This block allows you to cut glass into different shapes. This mod adds stairs and slabs for every type of glass.'

[[dependencies.glasscutter]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.glasscutter]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19]"
    ordering="NONE"
    side="BOTH"

[modproperties.glasscutter]
    catalogueItemIcon="glasscutter:glasscutter" #Optional support for Cataloque mod.
    configBackground="minecraft:textures/blocks/stone.png" #Optional support for Configured mod.
